# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
- job: Linux
  displayName: Linux Binary
  continueOnError: true
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  - script: dotnet build -c Release -r linux-x64 --self-contained true UI.Console/UI.Console.csproj
    displayName: 'dotnet build Release'
  - script: dotnet publish -r linux-x64 --self-contained true -c Release -o distrib/cli/lin/ UI.Console/UI.Console.csproj /p:PublishTrimmed=true; PublishSingleFile=true
    displayName: 'publish linux binary'
  
- job: Windows
  displayName: Windows Binary
  continueOnError: true
  pool:
    vmImage: 'windows-2022'
  steps:
  - script: dotnet restore
    displayName: 'dotnet restore'
  - script: dotnet build -c Release -r win-x64 --self-contained true UI.WinForms.Msil/UI.WinForms.Msil.csproj
    displayName: 'dotnet build Release'
  - script: dotnet publish -r win-x64 --self-contained true -c Release -o distrib/gui/win/ UI.WinForms.Msil/UI.WinForms.Msil.csproj /p:PublishTrimmed=false; PublishSingleFile=true
    displayName: 'publish windows binary'
