namespace UI.Avalonia.Utils.ColorPalette;

// generated from https://react.fluentui.dev/?path=/docs/theme-colors--page
public interface IPalette
{
    string NeutralForeground1 { get; }
    string NeutralForeground1Hover { get; }
    string NeutralForeground1Pressed { get; }
    string NeutralForeground1Selected { get; }
    string NeutralForeground2 { get; }
    string NeutralForeground2Hover { get; }
    string NeutralForeground2Pressed { get; }
    string NeutralForeground2Selected { get; }
    string NeutralForeground2BrandHover { get; }
    string NeutralForeground2BrandPressed { get; }
    string NeutralForeground2BrandSelected { get; }
    string NeutralForeground3 { get; }
    string NeutralForeground3Hover { get; }
    string NeutralForeground3Pressed { get; }
    string NeutralForeground3Selected { get; }
    string NeutralForeground3BrandHover { get; }
    string NeutralForeground3BrandPressed { get; }
    string NeutralForeground3BrandSelected { get; }
    string NeutralForeground4 { get; }
    string NeutralForegroundDisabled { get; }
    string NeutralForegroundInvertedDisabled { get; }
    string BrandForegroundLink { get; }
    string BrandForegroundLinkHover { get; }
    string BrandForegroundLinkPressed { get; }
    string BrandForegroundLinkSelected { get; }
    string NeutralForeground2Link { get; }
    string NeutralForeground2LinkHover { get; }
    string NeutralForeground2LinkPressed { get; }
    string NeutralForeground2LinkSelected { get; }
    string CompoundBrandForeground1 { get; }
    string CompoundBrandForeground1Hover { get; }
    string CompoundBrandForeground1Pressed { get; }
    string BrandForeground1 { get; }
    string BrandForeground2 { get; }
    string BrandForeground2Hover { get; }
    string BrandForeground2Pressed { get; }
    string NeutralForeground1Static { get; }
    string NeutralForegroundStaticInverted { get; }
    string NeutralForegroundInverted { get; }
    string NeutralForegroundInvertedHover { get; }
    string NeutralForegroundInvertedPressed { get; }
    string NeutralForegroundInvertedSelected { get; }
    string NeutralForegroundInverted2 { get; }
    string NeutralForegroundOnBrand { get; }
    string NeutralForegroundInvertedLink { get; }
    string NeutralForegroundInvertedLinkHover { get; }
    string NeutralForegroundInvertedLinkPressed { get; }
    string NeutralForegroundInvertedLinkSelected { get; }
    string BrandForegroundInverted { get; }
    string BrandForegroundInvertedHover { get; }
    string BrandForegroundInvertedPressed { get; }
    string BrandForegroundOnLight { get; }
    string BrandForegroundOnLightHover { get; }
    string BrandForegroundOnLightPressed { get; }
    string BrandForegroundOnLightSelected { get; }
    string NeutralBackground1 { get; }
    string NeutralBackground1Hover { get; }
    string NeutralBackground1Pressed { get; }
    string NeutralBackground1Selected { get; }
    string NeutralBackground2 { get; }
    string NeutralBackground2Hover { get; }
    string NeutralBackground2Pressed { get; }
    string NeutralBackground2Selected { get; }
    string NeutralBackground3 { get; }
    string NeutralBackground3Hover { get; }
    string NeutralBackground3Pressed { get; }
    string NeutralBackground3Selected { get; }
    string NeutralBackground4 { get; }
    string NeutralBackground4Hover { get; }
    string NeutralBackground4Pressed { get; }
    string NeutralBackground4Selected { get; }
    string NeutralBackground5 { get; }
    string NeutralBackground5Hover { get; }
    string NeutralBackground5Pressed { get; }
    string NeutralBackground5Selected { get; }
    string NeutralBackground6 { get; }
    string NeutralBackgroundInverted { get; }
    string NeutralBackgroundStatic { get; }
    string NeutralBackgroundAlpha { get; }
    string NeutralBackgroundAlpha2 { get; }
    string SubtleBackground { get; }
    string SubtleBackgroundHover { get; }
    string SubtleBackgroundPressed { get; }
    string SubtleBackgroundSelected { get; }
    string SubtleBackgroundLightAlphaHover { get; }
    string SubtleBackgroundLightAlphaPressed { get; }
    string SubtleBackgroundLightAlphaSelected { get; }
    string SubtleBackgroundInverted { get; }
    string SubtleBackgroundInvertedHover { get; }
    string SubtleBackgroundInvertedPressed { get; }
    string SubtleBackgroundInvertedSelected { get; }
    string TransparentBackground { get; }
    string TransparentBackgroundHover { get; }
    string TransparentBackgroundPressed { get; }
    string TransparentBackgroundSelected { get; }
    string NeutralBackgroundDisabled { get; }
    string NeutralBackgroundInvertedDisabled { get; }
    string NeutralStencil1 { get; }
    string NeutralStencil2 { get; }
    string NeutralStencil1Alpha { get; }
    string NeutralStencil2Alpha { get; }
    string BackgroundOverlay { get; }
    string ScrollbarOverlay { get; }
    string BrandBackground { get; }
    string BrandBackgroundHover { get; }
    string BrandBackgroundPressed { get; }
    string BrandBackgroundSelected { get; }
    string CompoundBrandBackground { get; }
    string CompoundBrandBackgroundHover { get; }
    string CompoundBrandBackgroundPressed { get; }
    string BrandBackgroundStatic { get; }
    string BrandBackground2 { get; }
    string BrandBackground2Hover { get; }
    string BrandBackground2Pressed { get; }
    string BrandBackgroundInverted { get; }
    string BrandBackgroundInvertedHover { get; }
    string BrandBackgroundInvertedPressed { get; }
    string BrandBackgroundInvertedSelected { get; }
    string NeutralStrokeAccessible { get; }
    string NeutralStrokeAccessibleHover { get; }
    string NeutralStrokeAccessiblePressed { get; }
    string NeutralStrokeAccessibleSelected { get; }
    string NeutralStroke1 { get; }
    string NeutralStroke1Hover { get; }
    string NeutralStroke1Pressed { get; }
    string NeutralStroke1Selected { get; }
    string NeutralStroke2 { get; }
    string NeutralStroke3 { get; }
    string NeutralStrokeSubtle { get; }
    string NeutralStrokeOnBrand { get; }
    string NeutralStrokeOnBrand2 { get; }
    string NeutralStrokeOnBrand2Hover { get; }
    string NeutralStrokeOnBrand2Pressed { get; }
    string NeutralStrokeOnBrand2Selected { get; }
    string BrandStroke1 { get; }
    string BrandStroke2 { get; }
    string BrandStroke2Hover { get; }
    string BrandStroke2Pressed { get; }
    string BrandStroke2Contrast { get; }
    string CompoundBrandStroke { get; }
    string CompoundBrandStrokeHover { get; }
    string CompoundBrandStrokePressed { get; }
    string NeutralStrokeDisabled { get; }
    string NeutralStrokeInvertedDisabled { get; }
    string TransparentStroke { get; }
    string TransparentStrokeInteractive { get; }
    string TransparentStrokeDisabled { get; }
    string NeutralStrokeAlpha { get; }
    string NeutralStrokeAlpha2 { get; }
    string StrokeFocus1 { get; }
    string StrokeFocus2 { get; }
    string NeutralShadowAmbient { get; }
    string NeutralShadowKey { get; }
    string NeutralShadowAmbientLighter { get; }
    string NeutralShadowKeyLighter { get; }
    string NeutralShadowAmbientDarker { get; }
    string NeutralShadowKeyDarker { get; }
    string BrandShadowAmbient { get; }
    string BrandShadowKey { get; }
    string PaletteRedBackground1 { get; }
    string PaletteRedBackground2 { get; }
    string PaletteRedBackground3 { get; }
    string PaletteRedForeground1 { get; }
    string PaletteRedForeground2 { get; }
    string PaletteRedForeground3 { get; }
    string PaletteRedBorderActive { get; }
    string PaletteRedBorder1 { get; }
    string PaletteRedBorder2 { get; }
    string PaletteGreenBackground1 { get; }
    string PaletteGreenBackground2 { get; }
    string PaletteGreenBackground3 { get; }
    string PaletteGreenForeground1 { get; }
    string PaletteGreenForeground2 { get; }
    string PaletteGreenForeground3 { get; }
    string PaletteGreenBorderActive { get; }
    string PaletteGreenBorder1 { get; }
    string PaletteGreenBorder2 { get; }
    string PaletteDarkOrangeBackground1 { get; }
    string PaletteDarkOrangeBackground2 { get; }
    string PaletteDarkOrangeBackground3 { get; }
    string PaletteDarkOrangeForeground1 { get; }
    string PaletteDarkOrangeForeground2 { get; }
    string PaletteDarkOrangeForeground3 { get; }
    string PaletteDarkOrangeBorderActive { get; }
    string PaletteDarkOrangeBorder1 { get; }
    string PaletteDarkOrangeBorder2 { get; }
    string PaletteYellowBackground1 { get; }
    string PaletteYellowBackground2 { get; }
    string PaletteYellowBackground3 { get; }
    string PaletteYellowForeground1 { get; }
    string PaletteYellowForeground2 { get; }
    string PaletteYellowForeground3 { get; }
    string PaletteYellowBorderActive { get; }
    string PaletteYellowBorder1 { get; }
    string PaletteYellowBorder2 { get; }
    string PaletteBerryBackground1 { get; }
    string PaletteBerryBackground2 { get; }
    string PaletteBerryBackground3 { get; }
    string PaletteBerryForeground1 { get; }
    string PaletteBerryForeground2 { get; }
    string PaletteBerryForeground3 { get; }
    string PaletteBerryBorderActive { get; }
    string PaletteBerryBorder1 { get; }
    string PaletteBerryBorder2 { get; }
    string PaletteLightGreenBackground1 { get; }
    string PaletteLightGreenBackground2 { get; }
    string PaletteLightGreenBackground3 { get; }
    string PaletteLightGreenForeground1 { get; }
    string PaletteLightGreenForeground2 { get; }
    string PaletteLightGreenForeground3 { get; }
    string PaletteLightGreenBorderActive { get; }
    string PaletteLightGreenBorder1 { get; }
    string PaletteLightGreenBorder2 { get; }
    string PaletteMarigoldBackground1 { get; }
    string PaletteMarigoldBackground2 { get; }
    string PaletteMarigoldBackground3 { get; }
    string PaletteMarigoldForeground1 { get; }
    string PaletteMarigoldForeground2 { get; }
    string PaletteMarigoldForeground3 { get; }
    string PaletteMarigoldBorderActive { get; }
    string PaletteMarigoldBorder1 { get; }
    string PaletteMarigoldBorder2 { get; }
    string PaletteRedForegroundInverted { get; }
    string PaletteGreenForegroundInverted { get; }
    string PaletteYellowForegroundInverted { get; }
    string PaletteDarkRedBackground2 { get; }
    string PaletteDarkRedForeground2 { get; }
    string PaletteDarkRedBorderActive { get; }
    string PaletteCranberryBackground2 { get; }
    string PaletteCranberryForeground2 { get; }
    string PaletteCranberryBorderActive { get; }
    string PalettePumpkinBackground2 { get; }
    string PalettePumpkinForeground2 { get; }
    string PalettePumpkinBorderActive { get; }
    string PalettePeachBackground2 { get; }
    string PalettePeachForeground2 { get; }
    string PalettePeachBorderActive { get; }
    string PaletteGoldBackground2 { get; }
    string PaletteGoldForeground2 { get; }
    string PaletteGoldBorderActive { get; }
    string PaletteBrassBackground2 { get; }
    string PaletteBrassForeground2 { get; }
    string PaletteBrassBorderActive { get; }
    string PaletteBrownBackground2 { get; }
    string PaletteBrownForeground2 { get; }
    string PaletteBrownBorderActive { get; }
    string PaletteForestBackground2 { get; }
    string PaletteForestForeground2 { get; }
    string PaletteForestBorderActive { get; }
    string PaletteSeafoamBackground2 { get; }
    string PaletteSeafoamForeground2 { get; }
    string PaletteSeafoamBorderActive { get; }
    string PaletteDarkGreenBackground2 { get; }
    string PaletteDarkGreenForeground2 { get; }
    string PaletteDarkGreenBorderActive { get; }
    string PaletteLightTealBackground2 { get; }
    string PaletteLightTealForeground2 { get; }
    string PaletteLightTealBorderActive { get; }
    string PaletteTealBackground2 { get; }
    string PaletteTealForeground2 { get; }
    string PaletteTealBorderActive { get; }
    string PaletteSteelBackground2 { get; }
    string PaletteSteelForeground2 { get; }
    string PaletteSteelBorderActive { get; }
    string PaletteBlueBackground2 { get; }
    string PaletteBlueForeground2 { get; }
    string PaletteBlueBorderActive { get; }
    string PaletteRoyalBlueBackground2 { get; }
    string PaletteRoyalBlueForeground2 { get; }
    string PaletteRoyalBlueBorderActive { get; }
    string PaletteCornflowerBackground2 { get; }
    string PaletteCornflowerForeground2 { get; }
    string PaletteCornflowerBorderActive { get; }
    string PaletteNavyBackground2 { get; }
    string PaletteNavyForeground2 { get; }
    string PaletteNavyBorderActive { get; }
    string PaletteLavenderBackground2 { get; }
    string PaletteLavenderForeground2 { get; }
    string PaletteLavenderBorderActive { get; }
    string PalettePurpleBackground2 { get; }
    string PalettePurpleForeground2 { get; }
    string PalettePurpleBorderActive { get; }
    string PaletteGrapeBackground2 { get; }
    string PaletteGrapeForeground2 { get; }
    string PaletteGrapeBorderActive { get; }
    string PaletteLilacBackground2 { get; }
    string PaletteLilacForeground2 { get; }
    string PaletteLilacBorderActive { get; }
    string PalettePinkBackground2 { get; }
    string PalettePinkForeground2 { get; }
    string PalettePinkBorderActive { get; }
    string PaletteMagentaBackground2 { get; }
    string PaletteMagentaForeground2 { get; }
    string PaletteMagentaBorderActive { get; }
    string PalettePlumBackground2 { get; }
    string PalettePlumForeground2 { get; }
    string PalettePlumBorderActive { get; }
    string PaletteBeigeBackground2 { get; }
    string PaletteBeigeForeground2 { get; }
    string PaletteBeigeBorderActive { get; }
    string PaletteMinkBackground2 { get; }
    string PaletteMinkForeground2 { get; }
    string PaletteMinkBorderActive { get; }
    string PalettePlatinumBackground2 { get; }
    string PalettePlatinumForeground2 { get; }
    string PalettePlatinumBorderActive { get; }
    string PaletteAnchorBackground2 { get; }
    string PaletteAnchorForeground2 { get; }
    string PaletteAnchorBorderActive { get; }
    string StatusSuccessBackground1 { get; }
    string StatusSuccessBackground2 { get; }
    string StatusSuccessBackground3 { get; }
    string StatusSuccessForeground1 { get; }
    string StatusSuccessForeground2 { get; }
    string StatusSuccessForeground3 { get; }
    string StatusSuccessForegroundInverted { get; }
    string StatusSuccessBorderActive { get; }
    string StatusSuccessBorder1 { get; }
    string StatusSuccessBorder2 { get; }
    string StatusWarningBackground1 { get; }
    string StatusWarningBackground2 { get; }
    string StatusWarningBackground3 { get; }
    string StatusWarningForeground1 { get; }
    string StatusWarningForeground2 { get; }
    string StatusWarningForeground3 { get; }
    string StatusWarningForegroundInverted { get; }
    string StatusWarningBorderActive { get; }
    string StatusWarningBorder1 { get; }
    string StatusWarningBorder2 { get; }
    string StatusDangerBackground1 { get; }
    string StatusDangerBackground2 { get; }
    string StatusDangerBackground3 { get; }
    string StatusDangerForeground1 { get; }
    string StatusDangerForeground2 { get; }
    string StatusDangerForeground3 { get; }
    string StatusDangerForegroundInverted { get; }
    string StatusDangerBorderActive { get; }
    string StatusDangerBorder1 { get; }
    string StatusDangerBorder2 { get; }
}